### ISSUE TITLE
【ご相談】MV場面転換アニメーションの実装方法

### ISSUE THREAD

**Issue by yuminishi0309** [yuminishi0309/mavs-task-wp#13]
ページ：トップページ
箇所：MV

**実装したい内容：**
MVにいる時、スクロールするとMVから次のセクションへ1画面移動する

**現在までに検討・試行した内容：**
1）ライブラリscrollfy.jsを使用した実装
状態：検討のみ。未試行
→ライブラリを多数使用すると動作が重くなるかと考え、2) Vanilla JSでの実装を検討

2）Vanilla JSでの実装
想定した処理：mvのエリアにいる時にスクロールイベントがあると、次のセクションへ素早くスムーススクロールで移動
状態：試行するも、スピードが遅い、ガタ付きが出るなど、想定の動作にならず

**ご相談内容**
・今回の実装内容を上記 (2) で実現しようとした際、処理内容の方向性が合っているか。
・工数の制限もあるため、新しくライブラリを入れることがネガティブでないならば、ライブラリを使用した実装の採用を考えているが、パフォーマンスの観点でどうかご助言いただきたい。

**Comment by ShalCan** [comment]
@yuminishi0309 
完成させるのが大事なのでライブラリを使ってください！

**Comment by yuminishi0309** [comment]
@ShalCan 
そのようにいたします。ありがとうございます！
