### ISSUE TITLE
【ご相談】WP下層ページ作成で、作成した固定ページが表示されない

### ISSUE THREAD

**Issue by yuminishi0309** [yuminishi0309/mavs-task-wp#17]
概要：blogのカテゴリ別一覧の固定ページを作成したが、ページを確認するとトップページが表示される

現在のページ設定：
下層ページにおいて、下記のようにファイルを作成、テンプレートを選択

contactページ
・page-contact.php（固定ページ）
・page-contact-confirm.php（固定ページ）
・page-contact-complete.php（固定ページ）

blogページ
・全投稿の一覧ページ：page-blog.php（固定ページ）
・カテゴリ別の一覧ページ：category.php（固定ページ）
・記事投稿ページ：single.php

ご相談：
blogのカテゴリ別一覧ページは、category.phpのテンプレートを使用したが、固定ページの中でこのページのみ、管理画面から固定ページ一覧>表示をしても該当のページが表示されない（index.phpが表示される）。

想定される原因：
・ページに設定するテンプレートが誤っている
・スラッグの記載が誤っている（現在: “category”）
・ブログページはプラグイン追加時に設定するので今は設定しない

該当箇所：
https://github.com/yuminishi0309/mavs-task-wp/commit/6398c8fc30eddcf3545c348c9ba9a6f208277f77

**Comment by ShalCan** [comment]
@yuminishi0309 
今回はカスタム投稿タイプでブログを作成頂きたいです。
固定ページではなくプラグインで投稿の仕組みが作成される仕組みなので先に設定を終わらせてください。
Custom Post Type UI

そして作るべきテーマファイルはこちらになります。

- archive-カスタム投稿名.php（一覧）
- single-カスタム投稿名.php（詳細）
- taxonomy-タクソノミー名.php（カテゴリページ）

**Comment by yuminishi0309** [comment]
@ShalCan 

ご確認いただきありがとうございます。
プラグインの理解が不十分だったため、プラグイン設定は後からと認識してしまっていました。
先にプラグインでの設定を行います。

テーマファイルのご助言もありがとうございます。
